[tool.poetry]
name = "home-work-14-1"
version = "0.1.0"
description = ""
authors = ["Pavel Artiev <arijev@bk.ru>"]
readme = "README.md"
packages = [{include = "home_work_14"}]

[tool.poetry.dependencies]
python = "^3.13"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.1.1"
black = "^25.1.0"
mypy = "^1.14.1"
isort = "^6.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
